version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 80

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 8888
    volumes:
      - ./backend:/app